#!/bin/bash
#
# LTSI helper script to generate a git tree from the quilt LTSI tree
#
# Copyright 2012 Greg Kroah-Hartman
# Copyright 2012 Linux Foundation
#
# Licensed under the GPLv2 only.
#
#

echo "Not implemented yet, check back soon."
